name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: null
jobs:
  github-metrics:
    name: Generate GitHub Metrics for README
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member
          config_order: base.header, base.activity+community, isocalendar, habits, languages, notable, followup, reactions, stargazers

          base: header, activity
          base_indepth: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: no
          plugin_habits_charts: yes
          plugin_habits_languages_limit: 0

          plugin_languages: yes
          plugin_languages_skipped: BayesWitnesses/m2cgen
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: no
          plugin_notable_types: commit, pull_request, issue

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_display: absolute
          plugin_reactions_details: count

          plugin_stargazers: yes
