name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: null
concurrency:  # Queue workflows rather than overlap them
  group: metrics
jobs:
  github-metrics:
    name: Generate GitHub Metrics for README
    runs-on: ubuntu-latest
    steps:
      - name: Update base
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 5
          repositories_affiliations: owner, collaborator, organization_member
          config_order: base.header, base.activity+community

          base: header, activity
          base_indepth: yes

          filename: base.svg
          config_output: svg

      - name: Update isocalendar
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          filename: isocalendar.svg
          config_output: svg

      - name: Update habits
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_charts: yes

          filename: habits.svg
          config_output: svg

      - name: Update languages
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_languages: yes
          plugin_languages_skipped: BayesWitnesses/m2cgen
          plugin_languages_details: percentage, lines
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 0
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

          filename: languages.svg
          config_output: svg

      - name: Update notable
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: no
          plugin_notable_types: commit, pull_request, issue

          filename: notable.svg
          config_output: svg

      - name: Update followup
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_followup: yes
          plugin_followup_sections: user
          plugin_followup_indepth: yes

          filename: followup.svg
          config_output: svg

      - name: Update reactions
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_reactions: yes
          plugin_reactions_limit: 1000
          plugin_reactions_limit_issues: 1000
          plugin_reactions_display: absolute
          plugin_reactions_details: count

          filename: reactions.svg
          config_output: svg

      - name: Update stargazers
        uses: lowlighter/metrics@latest
        if: always()
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: StrikerRUS
          commits_authoring: StrikerRUS, ${{ secrets.AUTHOR_EMAILS }}
          config_timezone: Europe/Moscow
          plugins_errors_fatal: yes
          template: classic
          repositories: 1000
          repositories_batch: 3
          repositories_affiliations: owner, collaborator, organization_member

          base: ""

          plugin_stargazers: yes
          plugin_stargazers_days: 30

          filename: stargazers.svg
          config_output: svg
